In [2]:
import h2o
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from h2o.estimators import H2ORandomForestEstimator

h2o.init()

db = pd.read_csv('dataset/db_modelli.csv').drop(columns = 'Unnamed: 0')
# codifica
db['conc1_mean'] = np.where(db['conc1_mean'].values > 1, 1, 0)

target = 'conc1_mean'
predictors = db.columns.to_list()
predictors.remove(target)
predictors.remove('test_cas')

# categorical to factors
db_h = h2o.H2OFrame(db)
# occorre
for i in db.columns:
    if db[i].dtypes == 'object':
        db_h[i] = db_h[i].asfactor()

db_h['conc1_mean'] = db_h['conc1_mean'].asfactor()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
  Starting server from C:\Users\Simone\Anaconda3\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\Simone\AppData\Local\Temp\tmpltkf9tp0
  JVM stdout: C:\Users\Simone\AppData\Local\Temp\tmpltkf9tp0\h2o_Simone_started_from_python.out
  JVM stderr: C:\Users\Simone\AppData\Local\Temp\tmpltkf9tp0\h2o_Simone_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Europe/Berlin
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.30.0.5
H2O_cluster_version_age:    24 days
H2O_cluster_name:           H2O_from_python_Simone_6h33k8
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2.643 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.7 final
--------------------------  ---------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [4]:
train, test = db_h.split_frame(ratios = [0.7])

mod = H2ORandomForestEstimator(seed = 123)
mod.train(x = predictors, y = target, training_frame = train)

model_path = h2o.save_model(model=mod, path="C:\\Users\\Simone\\Desktop\\MLTOX-Simone\\Grid_depth", force=True)
print(model_path)

drf Model Build progress: |███████████████████████████████████████████████| 100%
C:\Users\Simone\Desktop\MLTOX-Simone\Grid_depth\DRF_model_python_1594634903657_32

In [11]:
saved_model = h2o.load_model('C:\\Users\\Simone\\Desktop\\MLTOX-Simone\\Grid_depth\\DRF_model_python_1594634903657_32')
saved_model

In [14]:
train, test = db_h.split_frame(ratios = [0.7])
saved_model.model_performance(test)

ModelMetricsBinomial: drf
** Reported on test data. **

MSE: 0.0413532465429109
RMSE: 0.2033549766858704
LogLoss: 0.16516027290878255
Mean Per-Class Error: 0.04620136199083569
AUC: 0.986325373952336
AUCPR: 0.9904837651417752
Gini: 0.972650747904672

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.49696682948619125:

               0       1   Error             Rate
0      0  2379.0   186.0  0.0725   (186.0/2565.0)
1      1   114.0  4275.0   0.026   (114.0/4389.0)
2  Total  2493.0  4461.0  0.0431   (300.0/6954.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.496967     0.966102  209.0
1                        max f2   0.372760     0.973336  243.0
2                  max f0point5   0.646964     0.969114  172.0
3                  max accuracy   0.499369     0.956859  208.0
4                 max precision   0.987380     0.998682   15.0
5                    max recall   0.022219     1.000000  384.0
6               max specificity   0.999981     0.999220    0.0
7              max absolute_mcc   0.499369     0.907033  208.0
8    max min_per_class_accuracy   0.610244     0.952837  181.0
9   max mean_per_class_accuracy   0.569819     0.953799  190.0
10                      max tns   0.999981  2563.000000    0.0
11                      max fns   0.999981  3801.000000    0.0
12                      max fps   0.000010  2565.000000  399.0
13                      max tps   0.022219  4389.000000  384.0
14                      max tnr   0.999981     0.999220    0.0
15                      max fnr   0.999981     0.866029    0.0
16                      max fpr   0.000010     1.000000  399.0
17                      max tpr   0.022219     1.000000  384.0

Gains/Lift Table: Avg response rate: 63,11 %, avg score: 63,11 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.077366,1.000000,1.578526,1.578526,0.996283,1.000000,0.996283,1.000000,0.122123,0.122123,57.852556,57.852556
1,,2,0.100086,0.999222,1.584416,1.579863,1.000000,0.999592,0.997126,0.999907,0.035999,0.158123,58.441558,57.986267
2,,3,0.151136,0.996667,1.584416,1.581401,1.000000,0.998103,0.998097,0.999298,0.080884,0.239007,58.441558,58.140052
3,,4,0.200029,0.990162,1.584416,1.582137,1.000000,0.994081,0.998562,0.998023,0.077466,0.316473,58.441558,58.213749
4,,5,0.300259,0.972000,1.570776,1.578345,0.991392,0.980762,0.996169,0.992261,0.157439,0.473912,57.077643,57.834503
5,,6,0.401927,0.940000,1.562005,1.574212,0.985856,0.956672,0.993560,0.983258,0.158806,0.632718,56.200518,57.421183
6,,7,0.500000,0.870090,1.551891,1.569834,0.979472,0.909791,0.990797,0.968848,0.152199,0.784917,55.189092,56.983368
7,,8,0.599942,0.682748,1.436233,1.547578,0.906475,0.793819,0.976750,0.939690,0.143541,0.928458,43.623283,54.757754
8,,9,0.700029,0.266625,0.621473,1.415168,0.392241,0.463302,0.893180,0.871579,0.062201,0.990658,-37.852665,41.516823
9,,10,0.799971,0.085611,0.070672,1.247197,0.044604,0.161721,0.787165,0.782895,0.007063,0.997722,-92.932823,24.719681
10,,11,0.900201,0.020000,0.022732,1.110863,0.014347,0.045793,0.701118,0.700824,0.002278,1.000000,-97.726807,11.086262
11,,12,1.000000,0.000000,0.000000,1.000000,0.000000,0.002472,0.631148,0.631130,0.000000,1.000000,-100.000000,0.000000

In [18]:
print(train.shape)
print(test.shape)

(16378, 20)
(6954, 20)